// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATSQQ3ITWNiqh93PsvlvmA2KNF0kPov5w',
    appId: '1:398690684185:web:487e2e21e1a93f4fb70988',
    messagingSenderId: '398690684185',
    projectId: 'social-media-d67eb',
    authDomain: 'social-media-d67eb.firebaseapp.com',
    storageBucket: 'social-media-d67eb.firebasestorage.app',
    measurementId: 'G-C8L30TQFFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpBFN7PiNjDaRRG0oQuqOSYD0XSoA6_SI',
    appId: '1:398690684185:android:2a58ccbdf9275dd3b70988',
    messagingSenderId: '398690684185',
    projectId: 'social-media-d67eb',
    storageBucket: 'social-media-d67eb.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLkV7SgaJiDsa0xX7ECaa9HxUkVPjDphg',
    appId: '1:398690684185:ios:97053ae260730c0fb70988',
    messagingSenderId: '398690684185',
    projectId: 'social-media-d67eb',
    storageBucket: 'social-media-d67eb.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATSQQ3ITWNiqh93PsvlvmA2KNF0kPov5w',
    appId: '1:398690684185:web:5ee03c18e9d6daa2b70988',
    messagingSenderId: '398690684185',
    projectId: 'social-media-d67eb',
    authDomain: 'social-media-d67eb.firebaseapp.com',
    storageBucket: 'social-media-d67eb.firebasestorage.app',
    measurementId: 'G-KL8V47TM0N',
  );
}
