// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7ADLUsGuTSNhLRgBLHLXHpH5DkXxRfLM',
    appId: '1:40848576098:web:d81363113a873ddca40b3b',
    messagingSenderId: '40848576098',
    projectId: 'social-media-e52bb',
    authDomain: 'social-media-e52bb.firebaseapp.com',
    storageBucket: 'social-media-e52bb.appspot.com',
    measurementId: 'G-X8WGJ5PQBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeqyxyPB3RctQoIVwWtnjkSu3wICB3-UU',
    appId: '1:40848576098:android:958b6d822b063c47a40b3b',
    messagingSenderId: '40848576098',
    projectId: 'social-media-e52bb',
    storageBucket: 'social-media-e52bb.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDRy1MZh7tKEq6CvjTWGKQTpNVTX_UlcU',
    appId: '1:40848576098:ios:f7d3e7f081811070a40b3b',
    messagingSenderId: '40848576098',
    projectId: 'social-media-e52bb',
    storageBucket: 'social-media-e52bb.appspot.com',
    iosBundleId: 'com.ravio-social.app',
  );
}
